# @format

name: Sync Repos (src/ only)

on:
  push:
    branches:
      - main
  # Optional: scheduled sync
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Sync `src/` to Deploy repo
        run: |
          git config --global user.email "ari.glikman@intersystems.com"
          git config --global user.name "InterSystems-Israel"

          # Clone the Deploy repo
          git clone https://${ORG_NAME}:${PAT}@github.com/${ORG_NAME}/Deploy.git

          # Copy only the `src` directory
          cp -r src Deploy/src

          cd Deploy
          git add src
          git commit -m "[ci skip] Sync src from ${REPO_NAME}" || echo "No changes to commit"
          git push origin main
        env:
          PAT: ${{ secrets.PAT }}
          ORG_NAME: ariglikman         # <-- replace with your GitHub username
          REPO_NAME: ${{ github.event.repository.name }}
